config/routes.rb
Rails.application.routes.draw do
  get 'weather/form'

  post 'weather/display'

  root 'weather#form'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def form
    @states = %w(PR GA WI IL CA)
    @states.sort!
  end

  def display
  if params[:city] != nil
      params[:city].gsub! " ", "_"
      end
      response = HTTParty.get("http://api.wunderground.com/api/#{ENV['wunderground_key']}/geolookup/conditions/q/#{params[:state]}/#{params[:city]}.json")

    if response['response']['error'] != nil
        flash[:notice] =  "None such a place!"
        redirect_to action: :form
    else
      @res = {city: response['location']['city'],
        state: response['location']['state'],
        country: response['location']['country'],
        updated: response['current_observation']['observation_time'],
        weather: response['current_observation']['weather'],
        weather_icon: response['current_observation']['icon_url'],
        temp: response['current_observation']['temp_f'],
        wind: response['current_observation']['wind_string'],
        more_link: response['current_observation']['forecast_url']}

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sunwatch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/display.html.erb
<div class="container">
    <div class="row">
	<div class="col-sm-12">
		<div class="well">
		        <h2><%= @res[:city] %>, <%= @res[:state] %> - <%= @res[:country] %></h2>
		        <h3><%= @res[:updated] %></h3>
		        <hr/>
		        <h3>
		            <img src="<%= @res[:weather_icon] %>" alt="<%= @res[:weather] %>"/>
		            <%= @res[:weather] %>
		        </h3>
		        <hr/>
		        <p class="lead">
		            <strong>Temp:</strong> <%= @res[:temp] %>
		        </p>
		        <p class="lead">
		            <strong>Wind:</strong> <%= @res[:wind] %>
		        </p>
			<p>
		            <a href="<%= @res[:more_link] %>" class="btn btn-info">More Forecasts</a>
		            <a href="/" class="btn btn-default">Back Home</a>
		        </p>
		    </div>
	</div>
    </div>
</div>

app/views/weather/form.html.erb
<div class="jumbotron">
  <div class="container">
	<div class="row">
	  <div class="col-sm-12">
		<h1>Sunwatch</h1>
		<p>An application for finding out the weather</p>
	  </div>
	</div>
  </div>
</div>
<div class="container">
  <div class="row">
	<div class="col-sm-12">
	<% if notice %>
    <div class="alert alert-danger">
      <p><%= notice %></p>
    </div>
	<% end %>
		
	  <%= form_tag weather_display_url do %>
    <div class="row">
	  <div class="col-sm-8">
	    <%= label_tag "city", "City", class: "control-label" %>
	    <%= text_field_tag :city, nil, placeholder: "Enter a City", class: "form-control" %>
	  </div>
		<div class="col-sm-4">
		    <%= label_tag "state", "State", class: "control-label" %>
		    <%= text_field_tag :state, nil, placeholder: "Enter a State, e.g.: LA", class: "form-control" %>
		</div>
    </div>
    <hr/>
    <%= submit_tag "Submit!", class: "btn btn-primary" %>
   <% end %>
	</div>
  </div>
</div>